#!/bin/bash
# count all files through recursion
count=0
dir=0
content=""
for temp in $*
do
    for file in `ls -R $temp`
    do
        if [ -d $file ]
        then
            dir=$[$dir + 1]
            content=${content}$file" "
        fi
        count=$[$count + 1]
    done
done
echo "All files: $count"
echo "directory: $dir"
echo "dir name: $content"
