#!/bin/bash
#!/bin/bash
# create bash shell automatically
# In this file, I want to create bash shell automatically
# and it is executable, but I encounted a few questions:
# such as: 
#    1.( for file in $* ) and (for file in "$@") and (for file in $@) 
#    are all useful. I could not use (for file in "$*"), because 
#    the '$*' is a string not the parameter array! 
read -p "Input sum:" sum

for((count=1;count<$sum;count++))
do
    if [ ! -e file$count ]
    then
        touch file$count
        chmod u+x file$count
        echo "#!/bin/bash" >> file$count
        echo "# " >> file$count
    else
        echo "file$count has existed!"
    fi
done
echo "$count files have been created!"
