#!/bin/bash
#Author:zhangtao
#Date & Time: 2015-12-31-00:30:33
#Description:Judge max number in 3 numbers
echo "Please enter three number:"
read -p "First:" n1
read -p "Second:" n2
read -p "Third:" n3
let Max=$n1
if [ $n2 -gt $Max ]
then
    Max=$n2
fi

if [ $n3 -gt $Max ]
then
    Max=$n3
fi
echo "Max num is: $Max"

