#!/bin/bash
# check file type
pwfile=/etc/shadow
if [ -d pwfile ]
then
    echo "$pwfile is a directory"
elif [ -f $pwfile ]
then
    echo "$pwfile is a normal file"
else
    echo "Unknow file type"
fi
if [ $1 -nt $2 ]
then
    echo "$1 is newer than $2"
else
    echo "$1 is older than $2"
fi
