#!/bin/bash
# iterating thtough mutiple directories

for file in /home/zhangtao/.b* /home/zhangtao/Document
do
    if [ -d "$file" ]
    then
        echo "$file is a directory"
    elif [ -f "$file" ]
    then
        echo "$file is a file"
    else
        echo "$file does not exist"
    fi
done


