#!/bin/bash
# output 9*9  multiplication table and redirect to a file

for (( var1 = 1; var1 <= 9; var1++ ))
do
    for (( var2 = 1; var2 <= $var1; var2++ ))
    do
        echo -n " $var2 * $var1 = $[$var1*$var2]  "
    done
    echo
done 
