#!/bin/bash
# exacting options and parameters

while [ -n "$1" ]
do
    case "$1" in
        -a)
            echo "Found the -a option"
            ;;
        -b)
            echo "Found the -b option"
            ;;
        -c)
            echo "Found the -c option"
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "$1 is not an option!"
            ;;
    esac
    shift
done

count=1
while [ -n "$1" ]
do
    echo "Patameter #$count is $1"
    count=$[$count+1]
    shift
done
