#!/bin/bash
# simple demonstration of the getopts command

while getopts :ab:c:d: opt
do
    case "$opt" in
        a)
            echo "Found the -a option" ;;
        b)
            echo "Found the -b option with value $OPTARG" ;;
        c)
            echo "Found the -c option with value $OPTARG" ;;
        d)
            echo "Found the -d option with value $OPTARG" ;;
        *)
            echo "Unknow option: $opt"
    esac
    echo "Location is $OPTIND"
done
