#!/bin/bash
# using the tee command for logging

tempfile=wrong

echo "This is the start of the test" | tee $tempfile
echo "This is the second o the test" | tee -a $tempfile
echo "THis is the end of the test" | tee -a $tempfile
