#!/bin/bash
#Author:zhangtao
#Date & Time: 2015-12-31-00:36:05
#Description: calculate even number between 0 and 100

#Method 1
sum=0
for i in {1..100}
do
    if [ $[$i % 2] -eq 0 ]
    then
        sum=$[$sum + $i]
    fi
done
echo "Sum is $sum"

#Method 2
sum=0
for i in {1..50}
do
    sum=$(($sum+2*$i))
done
echo "Sum is $sum"

#Method 3
let Sum=0
for i in $(seq 1 100)
do
    if [ $[$i%2] == 0 ]
    then
        let Sum+=$i
    fi
done
echo "the sum is $Sum"
