#!/bin/bash
#Author:Zhangtao
#Date & Time: 2016-01-15-23:17:26
#Description:Using zenity to create a menu
temp=`mktemp -t temp.XXXXXX`
temp2=`mktemp -t temp2.XXXXXX`

function diskspace() 
{
    df -hk > $temp
    zenity --text-info --title "Disk space" --filename=$temp \
        --width 750 --height 200
}

function whoseon() 
{
    who > $temp
    zenity --text-info --title "Logged in users" --filename=$temp \
        --width 500 --height 300
}

function memusage() 
{
    zenity --text-info --title "Memory usage" --filename=$temp \
        --width 300 --height 500
}

while [ 1 ]
do
    zenity --list --radiolist --title "Sys Admin Menu" --column \
        "Select" --column "Menu Item" FALSE "Display diskspace" FALSE  \
        "Display users" FALSE "Display memory usage" FALSE "Exit" > $temp2
    if [ $? -eq 1 ]
    then
        break
    fi

    selection=`cat $temp2`
    case $selection in 
        "Display diskspace")
            diskspace
            ;;
        "Display users")
            whoseon
            ;;
        "Display memory usage")
            memusage
            ;;
        "Exit")
            break
            ;;
        *)
            zenity --info "Sorry, invalid selection"
    esac
done

