#!/bin/bash
# create bash shell automatically version2
# In this file, I want to create bash shell automatically
# and it is executable, but I encounted a few questions:
# such as: 
#    1.( for file in $* ) and (for file in "$@") and (for file in $@) 
#    are all useful. I could not use (for file in "$*"), because 
#    the '$*' is a string not the parameter array! 
for file in "$@"
do
    if [ ! -e $file ]
    then
        /usr/bin/auto_add_shellhead $file
        echo "$file create success!"
    else
        echo "$file has existed! Create failed!"
    fi
done
